version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:

  AfterInstall:
    - location: installDependencies.sh
      timeout: 300
      runas: root
    - location: restartTheServer.sh
      timeout: 30
      runas: root